### ISSUE TITLE
3ccfg.exe link 404

### ISSUE THREAD

**Issue by SPdowns** [hackerb9/3C509B-nestor#1]
Hello, while trying to download the 3ccfg.exe it leads to a 404. This is in the readme btw

**Comment by SPdowns** [comment]
Found what I believe to be the issue. https://github.com/hackerb9/3C509B-nestor/blob/master/3C5x9x/3ccfg.exe?raw=true is the link for the first three 3ccfg.exe links. Further below, another link for the 3ccfg.exe is found to be working. https://github.com/hackerb9/3C509B-nestor/blob/master/3c5x9x/3ccfg.exe?raw=true - in the 3c5x9x the C is lowercase. That is all

**Comment by hackerb9** [comment]
Thank you for the detailed bug report!
